spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/keycloak
    username: keycloak
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/auth/realms/Propostas
          jwk-set-uri: http://localhost:18080/auth/realms/Propostas/protocol/openid-connect/certs

info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    name: '@project.name@'
    version: '@project.version@'
management:
  endpoint:
    health:
      show-details: always

#Rotina Cartão
associar:
  cartao:
    tempo:
      schedule: 20000